<a href="https://colab.research.google.com/github/devansh377/Devansh-portfolio/blob/main/House_price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('housing1.csv')
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values
print(X)
print(Y)

[[7420 4 2 ... 'no' 'yes' 'yes']
 [8960 4 4 ... 'no' 'yes' 'no']
 [9960 3 2 ... 'no' 'no' 'yes']
 ...
 [3620 2 1 ... 'no' 'no' 'no']
 [2910 3 1 ... 'no' 'no' 'no']
 [3850 3 1 ... 'no' 'no' 'no']]
[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615000  6580000  6510000  6510000  6510000  6475000
 

In [ ]:
pip install --upgrade scikit-learn

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
le=LabelEncoder()
for i in range(5,11):
  X[:,i]=le.fit_transform(X[:,i])
sc= StandardScaler()
X[:, 0:5]= sc.fit_transform(X[:,0:5])
print(X)


[[1.0467262882352133 1.4034193573588298 1.4218117367065486 ... 0 1 1]
 [1.7570095257333957 1.4034193573588298 5.405808633904846 ... 0 1 0]
 [2.218232407225722 0.047278311684073836 1.4218117367065486 ... 0 0 1]
 ...
 [-0.7059206614356268 -1.308862733990682 -0.5701867118926005 ... 0 0 0]
 [-1.0333889072951785 0.047278311684073836 -0.5701867118926005 ... 0 0 0]
 [-0.5998393986923918 0.047278311684073836 -0.5701867118926005 ... 0 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,random_state=0)
regressor.fit(X_train,Y_train)


RandomForestRegressor(random_state=0)

In [ ]:
y_pred= regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[ 3175410.          4585000.        ]
 [ 5543720.          6083000.        ]
 [ 4001970.          4007500.        ]
 [ 5711020.          6930000.        ]
 [ 3394930.          2940000.        ]
 [ 6701240.          6195000.        ]
 [ 4324180.          3535000.        ]
 [ 3738490.          2940000.        ]
 [ 3755080.          3500000.        ]
 [ 7998585.46666667  7980000.        ]
 [ 6295613.33333333  6755000.        ]
 [ 3465227.5         3990000.        ]
 [ 4035360.          3150000.        ]
 [ 4621050.          3290000.        ]
 [ 4463200.          4130000.        ]
 [ 2006322.5         2660000.        ]
 [ 4039647.5         4410000.        ]
 [ 4237100.          3710000.        ]
 [ 3447675.          3360000.        ]
 [ 3795680.          4270000.        ]
 [ 7346080.          5005000.        ]
 [ 6114885.          5383000.        ]
 [ 4113340.          6440000.        ]
 [ 3090988.83333333  1890000.        ]
 [ 6170430.          6125000.        ]
 [ 5142620.          5460